apiVersion: 1

datasources:
  - name: Armiarma
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: Armiarma
    isDefault: true
    editable: false

  - name: ArmiarmaDB
    type: postgres
    access: proxy
    url: db:5432
    database: armiarmadb
    user: user
    uid: ArmiarmaDB
    isDefault: false
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1400
    secureJsonData:
      password: 'password'
