{
 "title": "Armiarma Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Host", "query": "prometheus" },
   { "name": "Crawler", "label": "Crawler", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  { "title": "Crawlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Running Crawlers",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 1 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Total Active Nodes per Crawler",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (crawler_observed_client_distribution)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Client Observed Distribution",
   "type": "timeseries",
   "description": "Client distribution observed by the tool crawling the Eth2 Beaconchain network",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution{job=~\"$Crawler\"}"
    }
   ]
  },
  {
   "title": "Current Client Share",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of Directly Connected Nodes ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "host_connected_peers{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Supported Protocols",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "host_supported_protocols{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head Slot of the Crawler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "local_node_local_head_slot{job=~\"$Crawler\"}"
    }
   ]
  },
  { "title": "GossipSub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Peers per GossipSub Topics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "gossipsub_peers_per_topic{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Directly Connected Peers per Topic",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 27 },
   "targets": [
    {
     "expr": "gossipsub_peers_per_topic{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Directly Connected Peers per Topic (Table)",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "gossipsub_peers_per_topic{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Crawler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Client Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "crawler_observed_client_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Version Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "crawler_observed_client_version_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Popular Client Versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 37 },
   "targets": [
    {
     "expr": "crawler_observed_client_version_distribution{job=~\"$Crawler\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "timeseries",
   "description": "Nodes that are not deprecated, that we identified ",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(instance) (crawler_observed_client_distribution{job=~\"$Crawler\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Deprecated Peers",
   "type": "timeseries",
   "description": "distribution of the total of nodes that we have deprecated since the crawler was launched.\nNOTE: the distribution shows unique peers.",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "crawler_deprecated_nodes{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Deprecated Node Count",
   "type": "timeseries",
   "description": "From all the peers discovered in the network, the distribution shows the number of peers that are not deprected.",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 47 },
   "targets": [
    {
     "expr": "crawler_node_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Geo distribution",
   "type": "table",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 47 },
   "targets": [
    {
     "expr": "crawler_geographical_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Os Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "crawler_os_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Architecture Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "crawler_arch_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ip Hosting distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "crawler_hosted_peers_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Peering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Peers Attempted to Connect on Last Peerstore Iteration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "peering_peers_attempted_last_iteration{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taken Time to Perform the Iterations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "peering_peerstore_iteration_time_secs{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Distribution of the Error Category that Peers reported in the last Iterations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "peering_iteration_attempts_by_category_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Error Category Distribution Over the Non-Deprecated Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "peering_pruned_error_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dialling Error Distribution on Connection Attempts in Last Iteration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "peering_conn_error_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Distribution of the Non-Deprecated Peers",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "peering_total_conn_error_distribution{job=~\"$Crawler\", error_type!=\"--\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Peer Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Advertised Attesnets from Active peers",
   "type": "barchart",
   "description": "The number of attetation subnets that peers active in the last day advertise in their ENR.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "discovery_attnets_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Peers",
   "type": "timeseries",
   "description": "Distributions of how many ENR (nodes) where discovered in the last 24 hours",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "discovery_node_per_fork_distribution{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Allocated Memory (MB) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$Crawler\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "go_threads{job=~\"$Crawler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Geographic Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Active Peer Locations (World Map)",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {
     "rawSql": "SELECT \n  ips.lat AS latitude,\n  ips.lon AS longitude, \n  ips.country,\n  ips.city,\n  peer_info.network,\n  COUNT(DISTINCT peer_info.peer_id) AS peer_count\nFROM peer_info\nINNER JOIN ips ON peer_info.ip = ips.ip\nWHERE peer_info.deprecated = false\n  AND (\n    '${Crawler:raw}' = '.*'\n    OR (peer_info.network = 'Ethereum CL' AND '${Crawler:raw}' ~* '^crawler$|ethereum')\n    OR (peer_info.network = 'Polygon' AND '${Crawler:raw}' ~* 'polygon')\n    OR (peer_info.network = 'IPFS' AND '${Crawler:raw}' ~* 'ipfs')\n    OR (peer_info.network = 'Filecoin' AND '${Crawler:raw}' ~* 'filecoin')\n  )\nGROUP BY ips.lat, ips.lon, ips.country, ips.city, peer_info.network\nORDER BY peer_count DESC;"
    }
   ]
  }
 ]
}